server:
  port: 8000
spring:
  application:
    name: task
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/task?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

wechat:
  token: "study"

git:
  repository: "git@gitee.com:jcglqmoyx/report.git"

logging:
  file:
    name: app.log
